### ISSUE TITLE
Issue with localize on received_after

### ISSUE THREAD

**Issue by cdavi198** [mailosaur/mailosaur-python#17]
Currently having an issue where it tries to run localize on received_after. The timezone in messages_operations is being returned as ZoneInfo which appears to not have the method localize.

`AttributeError: 'backports.zoneinfo.ZoneInfo' object has no attribute 'localize'`

**Comment by andreagubellini** [comment]
@cdavi198 how did you manage to solve this? I'm having the same issue.

**Comment by jhudsonbbm** [comment]
I'm also experiencing this issue. Any suggestions?

**Comment by andreagubellini** [comment]
> I'm also experiencing this issue. Any suggestions?

I personally fixed by resetting the symlink with /etc/localtime and updating tzlocal
