### ISSUE TITLE
Raise specific exception

### ISSUE THREAD

**Issue by mjhanke** [mailosaur/mailosaur-python#8]
https://github.com/mailosaur/mailosaur-python/blob/c2276296b3c078e11e80d01942910e9968982cd5/mailosaur/operations/messages_operations.py#L190

This line should raise a MailosaurException, not a generic Exception

**Comment by hippyhorse** [comment]
Having discussed this we are going to retain a standard Exception for now.

**Comment by mjhanke** [comment]
Could you please share your reasoning for retaining the standard Exception?
